import "dotenv/config";
import { db } from "../lib/db";
import {
  alerts,
  disclosurePerformanceWindows,
  disclosures,
  politicianStats,
  politicians,
  priceHistory,
  researchSignals,
  watchlistItems,
  watchlists,
} from "../lib/db/schema";

async function main() {
  console.log("🌱 Starting Trawl seed...");
  console.log("🧹 Clearing existing demo records...");

  await db.delete(alerts);
  await db.delete(watchlistItems);
  await db.delete(watchlists);
  await db.delete(politicianStats);
  await db.delete(researchSignals);
  await db.delete(disclosurePerformanceWindows);
  await db.delete(priceHistory);
  await db.delete(disclosures);
  await db.delete(politicians);

  console.log("👤 Inserting politicians...");
  const politicianRows = await db
    .insert(politicians)
    .values([
      {
        fullName: "Nancy Pelosi",
        chamber: "house",
        party: "Democrat",
        state: "CA",
      },
      {
        fullName: "Dan Crenshaw",
        chamber: "house",
        party: "Republican",
        state: "TX",
      },
      {
        fullName: "Tommy Tuberville",
        chamber: "senate",
        party: "Republican",
        state: "AL",
      },
      {
        fullName: "Ron Wyden",
        chamber: "senate",
        party: "Democrat",
        state: "OR",
      },
      {
        fullName: "Angus King",
        chamber: "senate",
        party: "Independent",
        state: "ME",
      },
    ])
    .returning();

  const [pelosi, crenshaw, tuberville, wyden, king] = politicianRows;
  console.log(`✅ Inserted ${politicianRows.length} politicians.`);

  console.log("📄 Inserting disclosures...");
  const disclosureRows = await db
    .insert(disclosures)
    .values([
      {
        politicianId: pelosi.id,
        ticker: "NVDA",
        assetName: "NVIDIA Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-03-10T00:00:00Z"),
        filingDate: new Date("2025-04-04T00:00:00Z"),
        filingLagDays: 25,
        sourceUrl: "https://example.com/filing/nvda",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "PLTR",
        assetName: "Palantir Technologies",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2025-04-08T00:00:00Z"),
        filingDate: new Date("2025-04-12T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/pltr",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "TSLA",
        assetName: "Tesla, Inc.",
        assetType: "stock",
        tradeType: "sale",
        ownerType: "spouse",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2025-03-20T00:00:00Z"),
        filingDate: new Date("2025-04-14T00:00:00Z"),
        filingLagDays: 25,
        sourceUrl: "https://example.com/filing/tsla",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "MSFT",
        assetName: "Microsoft Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-04-01T00:00:00Z"),
        filingDate: new Date("2025-04-10T00:00:00Z"),
        filingLagDays: 9,
        sourceUrl: "https://example.com/filing/msft",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "AMZN",
        assetName: "Amazon.com, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 100001,
        amountMax: 250000,
        amountRangeLabel: "$100,001 - $250,000",
        tradeDate: new Date("2025-04-05T00:00:00Z"),
        filingDate: new Date("2025-04-15T00:00:00Z"),
        filingLagDays: 10,
        sourceUrl: "https://example.com/filing/amzn",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "GOOGL",
        assetName: "Alphabet Inc.",
        assetType: "stock",
        tradeType: "exchange",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-04-06T00:00:00Z"),
        filingDate: new Date("2025-04-13T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/googl",
        sourceLabel: "Official Filing",
      },

      {
        politicianId: crenshaw.id,
        ticker: "AMD",
        assetName: "Advanced Micro Devices, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-04-02T00:00:00Z"),
        filingDate: new Date("2025-04-09T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/amd",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "META",
        assetName: "Meta Platforms, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2025-03-28T00:00:00Z"),
        filingDate: new Date("2025-04-11T00:00:00Z"),
        filingLagDays: 14,
        sourceUrl: "https://example.com/filing/meta",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "AAPL",
        assetName: "Apple Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2025-04-07T00:00:00Z"),
        filingDate: new Date("2025-04-12T00:00:00Z"),
        filingLagDays: 5,
        sourceUrl: "https://example.com/filing/aapl",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "JPM",
        assetName: "JPMorgan Chase & Co.",
        assetType: "stock",
        tradeType: "sale",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-03-25T00:00:00Z"),
        filingDate: new Date("2025-04-16T00:00:00Z"),
        filingLagDays: 22,
        sourceUrl: "https://example.com/filing/jpm",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "AVGO",
        assetName: "Broadcom Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2025-04-03T00:00:00Z"),
        filingDate: new Date("2025-04-10T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/avgo",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "NFLX",
        assetName: "Netflix, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-03-30T00:00:00Z"),
        filingDate: new Date("2025-04-12T00:00:00Z"),
        filingLagDays: 13,
        sourceUrl: "https://example.com/filing/nflx",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "LMT",
        assetName: "Lockheed Martin Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-04-09T00:00:00Z"),
        filingDate: new Date("2026-04-13T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/lmt",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "ADBE",
        assetName: "Adobe Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-04T00:00:00Z"),
        filingDate: new Date("2026-04-14T00:00:00Z"),
        filingLagDays: 10,
        sourceUrl: "https://example.com/filing/adbe",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "XOM",
        assetName: "Exxon Mobil Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2026-04-01T00:00:00Z"),
        filingDate: new Date("2026-04-15T00:00:00Z"),
        filingLagDays: 14,
        sourceUrl: "https://example.com/filing/xom",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "COST",
        assetName: "Costco Wholesale Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-04-05T00:00:00Z"),
        filingDate: new Date("2026-04-11T00:00:00Z"),
        filingLagDays: 6,
        sourceUrl: "https://example.com/filing/cost",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "CRM",
        assetName: "Salesforce, Inc.",
        assetType: "stock",
        tradeType: "exchange",
        ownerType: "spouse",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-06T00:00:00Z"),
        filingDate: new Date("2026-04-16T00:00:00Z"),
        filingLagDays: 10,
        sourceUrl: "https://example.com/filing/crm",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "RTX",
        assetName: "RTX Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-10T00:00:00Z"),
        filingDate: new Date("2026-04-14T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/rtx",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "ORCL",
        assetName: "Oracle Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-04-11T00:00:00Z"),
        filingDate: new Date("2026-04-15T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/orcl",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "BAC",
        assetName: "Bank of America Corporation",
        assetType: "stock",
        tradeType: "sale",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-03-29T00:00:00Z"),
        filingDate: new Date("2026-04-13T00:00:00Z"),
        filingLagDays: 15,
        sourceUrl: "https://example.com/filing/bac",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "QQQ",
        assetName: "Invesco QQQ Trust",
        assetType: "etf",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-08T00:00:00Z"),
        filingDate: new Date("2026-04-15T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/qqq",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "PANW",
        assetName: "Palo Alto Networks, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2026-04-09T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 8,
        sourceUrl: "https://example.com/filing/panw",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "NOC",
        assetName: "Northrop Grumman Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-12T00:00:00Z"),
        filingDate: new Date("2026-04-16T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/noc",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "INTU",
        assetName: "Intuit Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-10T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/intu",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "CVX",
        assetName: "Chevron Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-07T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 10,
        sourceUrl: "https://example.com/filing/cvx",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "SPY",
        assetName: "SPDR S&P 500 ETF Trust",
        assetType: "etf",
        tradeType: "exchange",
        ownerType: "self",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2026-04-02T00:00:00Z"),
        filingDate: new Date("2026-04-12T00:00:00Z"),
        filingLagDays: 10,
        sourceUrl: "https://example.com/filing/spy",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "SNOW",
        assetName: "Snowflake Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 100001,
        amountMax: 250000,
        amountRangeLabel: "$100,001 - $250,000",
        tradeDate: new Date("2026-04-11T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 6,
        sourceUrl: "https://example.com/filing/snow",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "BA",
        assetName: "The Boeing Company",
        assetType: "stock",
        tradeType: "sale",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-01T00:00:00Z"),
        filingDate: new Date("2026-04-16T00:00:00Z"),
        filingLagDays: 15,
        sourceUrl: "https://example.com/filing/ba",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "CSCO",
        assetName: "Cisco Systems, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-04-12T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 5,
        sourceUrl: "https://example.com/filing/csco",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "UNH",
        assetName: "UnitedHealth Group Incorporated",
        assetType: "stock",
        tradeType: "sale",
        ownerType: "spouse",
        amountMin: 50001,
        amountMax: 100000,
        amountRangeLabel: "$50,001 - $100,000",
        tradeDate: new Date("2026-03-31T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 17,
        sourceUrl: "https://example.com/filing/unh",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "V",
        assetName: "Visa Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-13T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/v",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: pelosi.id,
        ticker: "MDB",
        assetName: "MongoDB, Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2026-04-14T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 3,
        sourceUrl: "https://example.com/filing/mdb",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: crenshaw.id,
        ticker: "GD",
        assetName: "General Dynamics Corporation",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2026-04-13T00:00:00Z"),
        filingDate: new Date("2026-04-17T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/gd",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: wyden.id,
        ticker: "SHOP",
        assetName: "Shopify Inc.",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-04-13T00:00:00Z"),
        filingDate: new Date("2025-04-17T00:00:00Z"),
        filingLagDays: 4,
        sourceUrl: "https://example.com/filing/shop",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: tuberville.id,
        ticker: "COP",
        assetName: "ConocoPhillips",
        assetType: "stock",
        tradeType: "purchase",
        ownerType: "spouse",
        amountMin: 1001,
        amountMax: 15000,
        amountRangeLabel: "$1,001 - $15,000",
        tradeDate: new Date("2025-04-10T00:00:00Z"),
        filingDate: new Date("2025-04-17T00:00:00Z"),
        filingLagDays: 7,
        sourceUrl: "https://example.com/filing/cop",
        sourceLabel: "Official Filing",
      },
      {
        politicianId: king.id,
        ticker: "BRK.B",
        assetName: "Berkshire Hathaway Inc. Class B",
        assetType: "stock",
        tradeType: "exchange",
        ownerType: "self",
        amountMin: 15001,
        amountMax: 50000,
        amountRangeLabel: "$15,001 - $50,000",
        tradeDate: new Date("2025-04-14T00:00:00Z"),
        filingDate: new Date("2025-04-17T00:00:00Z"),
        filingLagDays: 3,
        sourceUrl: "https://example.com/filing/brkb",
        sourceLabel: "Official Filing",
      },
    ])
    .returning();

  console.log(`✅ Inserted ${disclosureRows.length} disclosures.`);

  console.log("📈 Inserting research signals...");
  const signalRows = await db
    .insert(researchSignals)
    .values([
      {
        disclosureId: disclosureRows[0].id,
        politicianId: pelosi.id,
        ticker: "NVDA",
        score: "84.00",
        signalStatus: "active",
        primaryReason: "Historically strong performer",
        reasonSummary:
          "Historically strong performer, relevant sector overlap, and positive short-term momentum.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "12.00",
        filingFreshnessScore: "10.00",
        historicalPoliticianScore: "17.00",
        momentumScore: "9.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "6.00",
        userRelevanceScore: "4.00",
        signalDate: new Date("2026-04-16T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[1].id,
        politicianId: crenshaw.id,
        ticker: "PLTR",
        score: "78.00",
        signalStatus: "active",
        primaryReason: "Fast filing and strong theme alignment",
        reasonSummary:
          "Quick filing lag, strong defense-tech narrative, and strong recent momentum.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "8.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "10.00",
        momentumScore: "11.00",
        committeeRelevanceScore: "9.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-17T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[2].id,
        politicianId: tuberville.id,
        ticker: "TSLA",
        score: "52.00",
        signalStatus: "active",
        primaryReason: "Large sale worth reviewing",
        reasonSummary:
          "Large reported sale and recognizable ticker, but weaker signal quality than recent purchases.",
        tradeTypeScore: "8.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "9.00",
        historicalPoliticianScore: "6.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "3.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-18T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[3].id,
        politicianId: wyden.id,
        ticker: "MSFT",
        score: "73.00",
        signalStatus: "active",
        primaryReason: "Fresh purchase with strong quality profile",
        reasonSummary:
          "Fresh purchase with respectable filing lag and strong large-cap quality backdrop.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "13.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-19T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[4].id,
        politicianId: pelosi.id,
        ticker: "AMZN",
        score: "88.00",
        signalStatus: "active",
        primaryReason: "Large purchase with strong context",
        reasonSummary:
          "Large purchase, strong historical attention, and attractive short-term research setup.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "15.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "18.00",
        momentumScore: "9.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "5.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-20T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[5].id,
        politicianId: king.id,
        ticker: "GOOGL",
        score: "66.00",
        signalStatus: "active",
        primaryReason: "Portfolio rotation into megacap tech",
        reasonSummary:
          "Recent exchange into a large-cap technology name with moderate filing freshness and committee relevance.",
        tradeTypeScore: "12.00",
        tradeSizeScore: "10.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "5.00",
        userRelevanceScore: "4.00",
        signalDate: new Date("2026-04-21T00:00:00Z"),
      },

      {
        disclosureId: disclosureRows[6].id,
        politicianId: crenshaw.id,
        ticker: "AMD",
        score: "76.00",
        signalStatus: "active",
        primaryReason: "Fast semiconductor purchase",
        reasonSummary:
          "Fresh purchase in a high-interest semiconductor name with strong filing speed and momentum.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "10.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-22T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[7].id,
        politicianId: pelosi.id,
        ticker: "META",
        score: "82.00",
        signalStatus: "active",
        primaryReason: "Large tech purchase with follow-through potential",
        reasonSummary:
          "Large purchase in a megacap technology name with strong market attention and solid momentum backdrop.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "11.00",
        historicalPoliticianScore: "16.00",
        momentumScore: "9.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-23T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[8].id,
        politicianId: wyden.id,
        ticker: "AAPL",
        score: "71.00",
        signalStatus: "active",
        primaryReason: "Quick large-cap tech filing",
        reasonSummary:
          "Small but fresh purchase with excellent filing speed in a durable large-cap name.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-24T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[9].id,
        politicianId: tuberville.id,
        ticker: "JPM",
        score: "49.00",
        signalStatus: "active",
        primaryReason: "Moderate financial sale",
        reasonSummary:
          "Reported sale in a major bank with middling freshness and lower purchase-style signal quality.",
        tradeTypeScore: "8.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "9.00",
        historicalPoliticianScore: "6.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-25T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[10].id,
        politicianId: king.id,
        ticker: "AVGO",
        score: "79.00",
        signalStatus: "active",
        primaryReason: "Large AI-linked infrastructure buy",
        reasonSummary:
          "Large purchase in a leading infrastructure name with strong relevance to current AI and chip demand themes.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "10.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-26T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[11].id,
        politicianId: pelosi.id,
        ticker: "NFLX",
        score: "74.00",
        signalStatus: "active",
        primaryReason: "Consumer tech follow-up purchase",
        reasonSummary:
          "Fresh spouse purchase in a well-followed growth name with solid quality and moderate cluster support.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "15.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "5.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-27T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[12].id,
        politicianId: crenshaw.id,
        ticker: "LMT",
        score: "75.00",
        signalStatus: "active",
        primaryReason: "Fast defense filing",
        reasonSummary:
          "Very fresh purchase in a defense contractor with strong theme alignment and reliable large-cap profile.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "10.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "11.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-28T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[13].id,
        politicianId: wyden.id,
        ticker: "ADBE",
        score: "72.00",
        signalStatus: "active",
        primaryReason: "Quality software purchase",
        reasonSummary:
          "Recent software purchase with balanced filing freshness, durable fundamentals, and moderate committee overlap.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-04-29T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[14].id,
        politicianId: tuberville.id,
        ticker: "XOM",
        score: "63.00",
        signalStatus: "active",
        primaryReason: "Large energy accumulation",
        reasonSummary:
          "Large spouse purchase in a major energy producer with solid trade size and moderate freshness.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "11.00",
        historicalPoliticianScore: "7.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "2.00",
        userRelevanceScore: "2.00",
        signalDate: new Date("2026-04-30T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[15].id,
        politicianId: king.id,
        ticker: "COST",
        score: "69.00",
        signalStatus: "active",
        primaryReason: "Fresh defensive retail buy",
        reasonSummary:
          "Recent small purchase in a defensive consumer name with strong filing speed and stable quality profile.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "5.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-01T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[16].id,
        politicianId: pelosi.id,
        ticker: "CRM",
        score: "70.00",
        signalStatus: "active",
        primaryReason: "Rotation into enterprise software",
        reasonSummary:
          "Portfolio rotation into enterprise software with healthy freshness and durable large-cap business quality.",
        tradeTypeScore: "12.00",
        tradeSizeScore: "10.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "14.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-02T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[17].id,
        politicianId: crenshaw.id,
        ticker: "RTX",
        score: "77.00",
        signalStatus: "active",
        primaryReason: "Quick defense sector purchase",
        reasonSummary:
          "Fast filing in a defense-oriented name with strong sector relevance and decent momentum.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "10.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "10.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-03T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[18].id,
        politicianId: wyden.id,
        ticker: "ORCL",
        score: "68.00",
        signalStatus: "active",
        primaryReason: "Fast enterprise infrastructure trade",
        reasonSummary:
          "Very quick filing in a durable software and cloud infrastructure name with balanced quality signals.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "6.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-04T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[19].id,
        politicianId: tuberville.id,
        ticker: "BAC",
        score: "44.00",
        signalStatus: "active",
        primaryReason: "Small bank sale",
        reasonSummary:
          "Smaller reported sale with average filing delay and lower conviction setup than recent buys.",
        tradeTypeScore: "8.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "10.00",
        historicalPoliticianScore: "5.00",
        momentumScore: "4.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-05T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[20].id,
        politicianId: king.id,
        ticker: "QQQ",
        score: "67.00",
        signalStatus: "active",
        primaryReason: "Broad growth exposure added",
        reasonSummary:
          "ETF purchase adds diversified exposure to growth and technology leadership with solid freshness.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "7.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "5.00",
        clusterScore: "2.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-06T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[21].id,
        politicianId: pelosi.id,
        ticker: "PANW",
        score: "83.00",
        signalStatus: "active",
        primaryReason: "Large cybersecurity purchase",
        reasonSummary:
          "Large spouse purchase in a leading cybersecurity name with strong short-term research appeal.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "13.00",
        historicalPoliticianScore: "16.00",
        momentumScore: "9.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-07T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[22].id,
        politicianId: crenshaw.id,
        ticker: "NOC",
        score: "76.00",
        signalStatus: "active",
        primaryReason: "Defense contractor accumulation",
        reasonSummary:
          "Fresh purchase in a defense contractor with clear thematic alignment and quick disclosure timing.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "10.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-08T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[23].id,
        politicianId: wyden.id,
        ticker: "INTU",
        score: "73.00",
        signalStatus: "active",
        primaryReason: "Fresh software compounder buy",
        reasonSummary:
          "Recent purchase in a high-quality software compounder with balanced momentum and committee relevance.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-09T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[24].id,
        politicianId: tuberville.id,
        ticker: "CVX",
        score: "61.00",
        signalStatus: "active",
        primaryReason: "Energy major purchase",
        reasonSummary:
          "Moderately fresh purchase in a large integrated energy name with decent size and lower momentum support.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "7.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "2.00",
        userRelevanceScore: "2.00",
        signalDate: new Date("2026-05-10T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[25].id,
        politicianId: king.id,
        ticker: "SPY",
        score: "62.00",
        signalStatus: "active",
        primaryReason: "Broad market rotation",
        reasonSummary:
          "Exchange into broad market exposure with respectable freshness and lower single-name conviction.",
        tradeTypeScore: "12.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "12.00",
        historicalPoliticianScore: "7.00",
        momentumScore: "6.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-11T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[26].id,
        politicianId: pelosi.id,
        ticker: "SNOW",
        score: "86.00",
        signalStatus: "active",
        primaryReason: "Large cloud data purchase",
        reasonSummary:
          "Large purchase in a high-beta cloud platform name with strong research interest and fresh filing.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "15.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "17.00",
        momentumScore: "9.00",
        committeeRelevanceScore: "6.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-12T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[27].id,
        politicianId: crenshaw.id,
        ticker: "BA",
        score: "46.00",
        signalStatus: "active",
        primaryReason: "Industrial sale signal",
        reasonSummary:
          "Sale in a defense and aerospace name carries some relevance but weaker upside-style signal quality.",
        tradeTypeScore: "8.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "10.00",
        historicalPoliticianScore: "6.00",
        momentumScore: "4.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "0.00",
        userRelevanceScore: "0.00",
        signalDate: new Date("2026-05-13T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[28].id,
        politicianId: wyden.id,
        ticker: "CSCO",
        score: "67.00",
        signalStatus: "active",
        primaryReason: "Fast infrastructure tech buy",
        reasonSummary:
          "Fresh small purchase in a stable networking name with strong filing speed and moderate relevance.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "6.00",
        committeeRelevanceScore: "8.00",
        clusterScore: "2.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-14T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[29].id,
        politicianId: tuberville.id,
        ticker: "UNH",
        score: "50.00",
        signalStatus: "active",
        primaryReason: "Large healthcare sale",
        reasonSummary:
          "Large reported sale with recognizable defensive profile, but still less compelling than fresh buys.",
        tradeTypeScore: "8.00",
        tradeSizeScore: "14.00",
        filingFreshnessScore: "10.00",
        historicalPoliticianScore: "6.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "2.00",
        userRelevanceScore: "1.00",
        signalDate: new Date("2026-05-15T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[30].id,
        politicianId: king.id,
        ticker: "V",
        score: "72.00",
        signalStatus: "active",
        primaryReason: "Fresh payments leader purchase",
        reasonSummary:
          "Very fresh large-cap purchase in a dominant payments platform with balanced quality and momentum.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "7.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-16T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[31].id,
        politicianId: pelosi.id,
        ticker: "MDB",
        score: "81.00",
        signalStatus: "active",
        primaryReason: "Very fresh growth software buy",
        reasonSummary:
          "Extremely fresh spouse purchase in a high-interest software name with strong attention and upside profile.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "16.00",
        historicalPoliticianScore: "16.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "6.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-17T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[32].id,
        politicianId: crenshaw.id,
        ticker: "GD",
        score: "70.00",
        signalStatus: "active",
        primaryReason: "Small defense purchase filed quickly",
        reasonSummary:
          "Quickly filed purchase in a defense contractor with solid relevance despite smaller trade size.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "9.00",
        momentumScore: "6.00",
        committeeRelevanceScore: "9.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-18T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[33].id,
        politicianId: wyden.id,
        ticker: "SHOP",
        score: "74.00",
        signalStatus: "active",
        primaryReason: "Fresh commerce software purchase",
        reasonSummary:
          "Recent purchase in a strong commerce software platform with decent momentum and quality support.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "15.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "8.00",
        committeeRelevanceScore: "7.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-19T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[34].id,
        politicianId: tuberville.id,
        ticker: "COP",
        score: "59.00",
        signalStatus: "active",
        primaryReason: "Small energy purchase",
        reasonSummary:
          "Fresh smaller energy purchase with acceptable timing but lower overall conviction than larger tech buys.",
        tradeTypeScore: "18.00",
        tradeSizeScore: "7.00",
        filingFreshnessScore: "14.00",
        historicalPoliticianScore: "6.00",
        momentumScore: "4.00",
        committeeRelevanceScore: "4.00",
        clusterScore: "3.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-20T00:00:00Z"),
      },
      {
        disclosureId: disclosureRows[35].id,
        politicianId: king.id,
        ticker: "BRK.B",
        score: "65.00",
        signalStatus: "active",
        primaryReason: "Rotation into defensive compounder",
        reasonSummary:
          "Recent exchange into a diversified high-quality compounder with low drama but solid long-term profile.",
        tradeTypeScore: "12.00",
        tradeSizeScore: "11.00",
        filingFreshnessScore: "16.00",
        historicalPoliticianScore: "8.00",
        momentumScore: "5.00",
        committeeRelevanceScore: "6.00",
        clusterScore: "4.00",
        userRelevanceScore: "3.00",
        signalDate: new Date("2026-05-21T00:00:00Z"),
      },
    ])
    .returning();

  console.log(`✅ Inserted ${signalRows.length} research signals.`);
  console.log("🎉 Seed complete.");
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});